### PR TITLE
fix: handle lack of OAUTH permission from orgs

### LINKED ISSUE #40: Application gives an error when the user has no GH projects created
Google Chrome_Phcio07r

The error message logged into the dev console says:

```
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
window.console.error @ 488-881aff3ca3fb2fa9.js:1
```

### PR DESCRIPTION
**Pull request by smoya**
Fixes https://github.com/shapeitapp/shapeitapp/issues/40

Btw, I didn't find a way of excluding from the GraphQL result projects from orgs that didn't provide OAUTH permission to the user, so this is my best effort to fix the issue.

### CODE REVIEW

File: src/app/projects/page.js [hunk 1]
```diff
@@ -114,14 +114,29 @@ export default async function Projects() {
...
-  const orgProjects = responseData.viewer.organizations.nodes.map(org =>
-    org.projectsV2.nodes.map(project => ({
-      ownerType: 'org',
-      orgName: org.login,
-      orgUrl: org.url,
-      ...project
-    }))
-  ).flat()
+
+  const orgProjects = responseData.viewer.organizations.nodes.reduce((projectsResult, org) => {
```
Comment (smoya) [inline src/app/projects/page.js:118]: Maybe, in the future, we want to show a tooltip to the user mentioning it has not enough permissions so no projects are shown for that org.

Comment (Amzani) [reply src/app/projects/page.js:118]: @smoya what was the project that you didn't had permission to see, is it because you didn't granted the permission during auth to the org ?

Comment (smoya) [reply src/app/projects/page.js:118]: I did not grant permission (or ask permission to admins) on some orgs I belong to, so projects were not fetched from GH API (came as literal `null` value)

**Review by fmvilas — APPROVED** [review]
